swagger: "2.0"
info:
  version: 1.0.0
  title: Asset Download Page
  description: Asset Download Page APIs

consumes:
  - application/json
produces:
  - application/json

definitions:
  volume:
    required:
      - id
    properties:
      id:
        type: integer
      alias:
        type: string
      body:
        type: string
      creation:
        type: string
      doi:
        type: string
      name:
        type: string
      owners:
        type: array
        items:
          name:
            type: string
          id:
            type: integer
      permission:
        type: integer
      publicsharefull:
        type: boolean
      publicaccess:
        type: string
    
  video:
    required:
      - id
    properties:
      asset:
        $ref: "#/definitions/asset"
      container:
        $ref: "#/definitions/container"
      permission:
        type: integer
      segment:
        type: array
        items:
          type: integer

  asset:
    required:
      - id
    properties:
      id:
        type: integer
      classification:
        type: integer
      format:
        type: integer
      name:
        type: string
      permission:
        type: integer
      segment:
        type: array
        items:
          type: integer

  container:
    required:
      - id
    properties:
      id:
        type: integer
      name:
        type: string
      top:
        type: boolean

parameters:
  volumeid:
    name: volumeid
    in: path
    description: ID of the volume
    required: true
    type: string
  containerid:
    name: containerid
    in: path
    description: ID of the container
    required: false
    type: string
  segmentRange:
    name: segmentRange
    in: path
    description: Segment range
    required: false
    type: string
  assetid:
    name: assetid
    in: path
    description: ID of the asset
    required: false
    type: string

paths:
  
  /api/volume/{volumeid}:
    parameters:
      - $ref: "#/parameters/volumeid"

    get:
      description: Returns a volume by ID
      operationId: findVolumeById
      responses:
        default:
          description: Returns the volume data
          schema:
            $ref: "#/definitions/volume"

  /api/volume/{volumeid}/slot/{containerid}/{segmentRange}/asset/{assetid}:
    parameters:
      - $ref: "#/parameters/volumeid"
      - $ref: "#/parameters/containerid"
      - $ref: "#/parameters/segmentRange"
      - $ref: "#/parameters/assetid"

    get:
      description: Returns an video by ID
      operationId: findvideoById
      responses:
        default:
          description: Returns the video data
          schema:
            $ref: "#/definitions/video"

  /:
    get:
      produces:
        - text/html
      responses:
        default:
          description: Asset Download
          schema:
            type: file
            default:
              $ref: "asset-download.html"
